from __future__ import annotations

import contextlib
import io
import tempfile
import unittest
from pathlib import Path

from langchain_hancom_loader import webhook_url


class WebhookUrlCommandTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary_directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary_directory.cleanup)
        self.env_file = Path(self.temporary_directory.name) / "hancom-webhook.env"
        self.url = "https://generated.trycloudflare.com/hancom/webhook"
        self.env_file.write_text(
            f"# generated by Compose\nHANCOM_WEBHOOK_URL={self.url}\n",
            encoding="utf-8",
        )

    def test_reads_generated_url(self) -> None:
        self.assertEqual(webhook_url.read_webhook_url(self.env_file), self.url)

    def test_prints_copyable_environment_entry(self) -> None:
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            webhook_url.main(["--env-file", str(self.env_file)])

        self.assertEqual(output.getvalue(), f"HANCOM_WEBHOOK_URL={self.url}\n")

    def test_can_print_only_the_url(self) -> None:
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            webhook_url.main(["--env-file", str(self.env_file), "--value-only"])

        self.assertEqual(output.getvalue(), f"{self.url}\n")


if __name__ == "__main__":
    unittest.main()
