"""Print the webhook URL generated by the local development tunnel."""

from __future__ import annotations

import argparse
from pathlib import Path

DEFAULT_WEBHOOK_ENV_FILE = Path(".runtime/hancom-webhook.env")


def read_webhook_url(env_file: Path) -> str | None:
    """Return ``HANCOM_WEBHOOK_URL`` from a Compose-generated environment file."""
    try:
        lines = env_file.read_text(encoding="utf-8").splitlines()
    except OSError:
        return None

    for raw_line in lines:
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        key, separator, value = line.partition("=")
        if separator and key.strip() == "HANCOM_WEBHOOK_URL":
            resolved = value.strip().strip('"').strip("'")
            return resolved or None
    return None


def main(argv: list[str] | None = None) -> None:
    """Print a copyable environment-variable entry for the generated URL."""
    parser = argparse.ArgumentParser(
        description="Print the webhook URL generated by the local Compose tunnel."
    )
    parser.add_argument(
        "--env-file",
        type=Path,
        default=DEFAULT_WEBHOOK_ENV_FILE,
        help="Path to hancom-webhook.env (default: .runtime/hancom-webhook.env).",
    )
    parser.add_argument(
        "--value-only",
        action="store_true",
        help="Print only the URL instead of a HANCOM_WEBHOOK_URL= entry.",
    )
    args = parser.parse_args(argv)

    webhook_url = read_webhook_url(args.env_file)
    if webhook_url is None:
        parser.error(
            f"No HANCOM_WEBHOOK_URL found in {args.env_file}. "
            "Start deploy/compose.webhook.yaml first."
        )

    print(webhook_url if args.value_only else f"HANCOM_WEBHOOK_URL={webhook_url}")


if __name__ == "__main__":
    main()
